Chap 02-2

In [2]:
import gdown
gdown.download('https://bit.ly/3q9SZix', '20s_best_book.json',
               quiet=False)

Downloading...
From: https://bit.ly/3q9SZix
To: /content/20s_best_book.json
100%|██████████| 92.9k/92.9k [00:00<00:00, 33.3MB/s]

'20s_best_book.json'

In [3]:
import pandas as pd
books_df = pd.read_json('20s_best_book.json')
books_df.head()

,no,ranking,bookname,authors,publisher,publication_year,isbn13,addition_symbol,vol,class_no,class_nm,loan_count,bookImageURL
0,1,1,우리가 빛의 속도로 갈 수 없다면 :김초엽 소설,지은이: 김초엽,허블,2019,9791190090018,03810,,813.7,문학 > 한국문학 > 소설,461,https://image.aladin.co.kr/product/19359/16/co...
1,2,2,달러구트 꿈 백화점.이미예 장편소설,지은이: 이미예,팩토리나인,2020,9791165341909,03810,,813.7,문학 > 한국문학 > 소설,387,https://image.aladin.co.kr/product/24512/70/co...
2,3,3,지구에서 한아뿐 :정세랑 장편소설,지은이: 정세랑,난다,2019,9791188862290,03810,,813.7,문학 > 한국문학 > 소설,383,https://image.aladin.co.kr/product/19804/82/co...
3,4,4,"시선으로부터, :정세랑 장편소설",지은이: 정세랑,문학동네,2020,9788954672214,03810,,813.7,문학 > 한국문학 > 소설,370,https://image.aladin.co.kr/product/24131/37/co...
4,5,5,아몬드 :손원평 장편소설,지은이: 손원평,창비,2017,9788936434267,03810,,813.7,문학 > 한국문학 > 소설,365,http://image.aladin.co.kr/product/16839/4/cove...

https://drive.google.com/drive/folders/1wn1YYJHKQOMg3-sbiSSfjWgm9u73O5H1

In [18]:
import gdown
gdown.download('https://drive.google.com/u/0/uc?id=11mgancWHq69V1B177dnM0cmpzlblJd6_&export=download', '20s_best_book_2.json',quiet = False)

Downloading...
From: https://drive.google.com/u/0/uc?id=11mgancWHq69V1B177dnM0cmpzlblJd6_&export=download
To: /content/20s_best_book_2.json
100%|██████████| 103k/103k [00:00<00:00, 56.3MB/s]

'20s_best_book_2.json'

In [19]:
import pandas as pd
books2_df = pd.read_json('20s_best_book_2.json')
books2_df.head()

,no,ranking,bookname,authors,publisher,publication_year,isbn13,addition_symbol,vol,class_no,class_nm,loan_count,bookImageURL,bookDtlUrl
0,1,1,우리가 빛의 속도로 갈 수 없다면 :김초엽 소설,지은이: 김초엽,허블,2019,9791190090018,03810,,813.7,문학 > 한국문학 > 소설,479,https://image.aladin.co.kr/product/19359/16/co...,https://data4library.kr/bookV?seq=5430429
1,2,2,달러구트 꿈 백화점.이미예 장편소설,지은이: 이미예,팩토리나인,2020,9791165341909,03810,,813.7,문학 > 한국문학 > 소설,407,https://image.aladin.co.kr/product/24512/70/co...,https://data4library.kr/bookV?seq=5707051
2,3,3,지구에서 한아뿐 :정세랑 장편소설,지은이: 정세랑,난다,2019,9791188862290,03810,,813.7,문학 > 한국문학 > 소설,391,https://image.aladin.co.kr/product/19804/82/co...,https://data4library.kr/bookV?seq=5446546
3,4,4,"시선으로부터, :정세랑 장편소설",지은이: 정세랑,문학동네,2020,9788954672214,03810,,813.7,문학 > 한국문학 > 소설,379,https://image.aladin.co.kr/product/24131/37/co...,https://data4library.kr/bookV?seq=5674475
4,5,5,아몬드손원평 장편소설,손원평,창비,2017,9788936434267,03810,,813.7,문학 > 한국문학 > 소설,375,http://image.aladin.co.kr/product/16839/4/cove...,https://data4library.kr/bookV?seq=3423096

In [20]:
books = books_df[['no', 'ranking', 'bookname', 'authors', 'publisher', 'publication_year', 'isbn13']]
books.head()

,no,ranking,bookname,authors,publisher,publication_year,isbn13
0,1,1,우리가 빛의 속도로 갈 수 없다면 :김초엽 소설,지은이: 김초엽,허블,2019,9791190090018
1,2,2,달러구트 꿈 백화점.이미예 장편소설,지은이: 이미예,팩토리나인,2020,9791165341909
2,3,3,지구에서 한아뿐 :정세랑 장편소설,지은이: 정세랑,난다,2019,9791188862290
3,4,4,"시선으로부터, :정세랑 장편소설",지은이: 정세랑,문학동네,2020,9788954672214
4,5,5,아몬드 :손원평 장편소설,지은이: 손원평,창비,2017,9788936434267

In [21]:
books_df.loc[[0,1], ['bookname','authors']]

                      bookname   authors
0  우리가 빛의 속도로 갈 수 없다면 :김초엽 소설   지은이: 김초엽
1         달러구트 꿈 백화점.이미예 장편소설   지은이: 이미예

In [26]:
books_df.loc[0:1, 'bookname':'authors']

                      bookname   authors
0  우리가 빛의 속도로 갈 수 없다면 :김초엽 소설   지은이: 김초엽
1         달러구트 꿈 백화점.이미예 장편소설   지은이: 이미예

In [27]:
books = books_df.loc[:, 'no':'isbn13']
books.head()

,no,ranking,bookname,authors,publisher,publication_year,isbn13
0,1,1,우리가 빛의 속도로 갈 수 없다면 :김초엽 소설,지은이: 김초엽,허블,2019,9791190090018
1,2,2,달러구트 꿈 백화점.이미예 장편소설,지은이: 이미예,팩토리나인,2020,9791165341909
2,3,3,지구에서 한아뿐 :정세랑 장편소설,지은이: 정세랑,난다,2019,9791188862290
3,4,4,"시선으로부터, :정세랑 장편소설",지은이: 정세랑,문학동네,2020,9788954672214
4,5,5,아몬드 :손원평 장편소설,지은이: 손원평,창비,2017,9788936434267

In [28]:
books_df.loc[0:3, 'no':'authors']

   no  ranking                     bookname   authors
0   1        1  우리가 빛의 속도로 갈 수 없다면 :김초엽 소설   지은이: 김초엽
1   2        2         달러구트 꿈 백화점.이미예 장편소설   지은이: 이미예
2   3        3          지구에서 한아뿐 :정세랑 장편소설   지은이: 정세랑
3   4        4           시선으로부터, :정세랑 장편소설   지은이: 정세랑

loc은 인덱스 이름으로 찾는거고 iloc은 인덱스 몇번째 행인지로 찾는거임

In [31]:
books_df.loc[ ::2, 'no':'isbn13':2].head()

   no                     bookname publisher         isbn13
0   1  우리가 빛의 속도로 갈 수 없다면 :김초엽 소설         허블  9791190090018
2   3          지구에서 한아뿐 :정세랑 장편소설         난다  9791188862290
4   5               아몬드 :손원평 장편소설         창비  9788936434267
6   7          목소리를 드릴게요 :정세랑 소설집         아작  9791165300005
8   9                   선량한 차별주의자         창비  9788936477196

In [33]:
import requests
isbn = 9791190090018
url = 'http://www.yes24.com/Product/Search?domain=BOOK&query={}'
r = requests.get(url.format(isbn))

In [ ]:
print(r.text)

http://www.yes24.com/Product/Search?domain=BOOK&query=9791190090018

In [35]:
from bs4 import BeautifulSoup

soup = BeautifulSoup(r.text, 'html.parser')

In [36]:
prd_link = soup.find('a', attrs={'class':'gd_name'})
print(prd_link)

<a class="gd_name" href="/Product/Goods/74261416" onclick="setSCode('101_005_003_001');setGoodsClickExtraCodeHub('032', '9791190090018', '74261416', '0');">우리가 빛의 속도로 갈 수 없다면</a>

In [37]:
print(prd_link['href'])

/Product/Goods/74261416

In [ ]:
url = 'http://www.yes24.com'+prd_link['href']
r = requests.get(url)
print(r.text)

In [ ]:
soup = BeautifulSoup(r.text, 'html.parser')
prd_detail = soup.find('div', attrs={'id':'infoset_specific'})
print(prd_detail)

In [ ]:
prd_tr_list = prd_detail.find_all('tr')
print(prd_tr_list)

In [42]:
for tr in prd_tr_list:
  if tr.find('th').get_text() == '쪽수, 무게, 크기':
    page_td = tr.find('td').get_text()
    break

In [ ]:
print(page_td)

In [ ]:
print(page_td.split()[0])

In [49]:
import requests
isbn = 9791165341909
url = 'http://www.yes24.com/Product/Search?domain=BOOK&query={}'
r = requests.get(url.format(isbn))

In [50]:
from bs4 import BeautifulSoup

soup = BeautifulSoup(r.text, 'html.parser')

In [51]:
prd_link = soup.find('a', attrs={'class':'gd_name'})
print(prd_link)

<a class="gd_name" href="/Product/Goods/91065309" onclick="setSCode('101_005_003_001');setGoodsClickExtraCodeHub('032', '9791165341909', '91065309', '0');">달러구트 꿈 백화점 (레인보우 에디션)</a>

In [52]:
print(prd_link['href'])

/Product/Goods/91065309

In [ ]:
url = 'http://www.yes24.com'+prd_link['href']
r = requests.get(url)
print(r.text)

In [ ]:
soup = BeautifulSoup(r.text, 'html.parser')
prd_detail = soup.find('div', attrs={'id':'infoset_specific'})
print(prd_detail)

In [ ]:
prd_tr_list = prd_detail.find_all('tr')
print(prd_tr_list)

In [56]:
for tr in prd_tr_list:
  if tr.find('th').get_text() == '쪽수, 무게, 크기':
    page_td = tr.find('td').get_text()
    break

In [57]:
print(page_td)

300쪽 | 358g | 134*200*20mm

In [58]:
print(page_td.split()[0])

300쪽